### ISSUE TITLE
Object.extname is deprecated.

### ISSUE THREAD

**Issue by Hectormm** [nirix/atom-editor-settings#30] opened 2016-11-16 10:06 UTC
Argument to `path.extname` must be a string
```
Object.extname (C:\ProgramData\hmm\atom\app-1.13.0-beta3\resources\app.asar\src\electron-shims.js:20:10)
Object.loadAllConfigFiles (C:\Users\hmm\.atom\packages\editor-settings\lib\editor-settings.coffee:91:28)
Object.reconfigureCurrentEditor (C:\Users\hmm\.atom\packages\editor-settings\lib\editor-settings.coffee:58:23)
<unknown> (C:\Users\hmm\.atom\packages\editor-settings\lib\editor-settings.coffee:27:24)
Function.module.exports.Emitter.simpleDispatch (C:\ProgramData\hmm\atom\app-1.13.0-beta3\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
Emitter.emit (C:\ProgramData\hmm\atom\app-1.13.0-beta3\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
```

**Comment by ehbc221** [comment] 2017-02-19 15:51
Hi everybody. I noticed this deprecation since i have updated Atom and i don't really know how to fix it.
If anybody got an idea to solve it, i'll be very happy!

**Comment by ehbc221** [comment] 2017-02-19 15:52
Hi everybody. I noticed this deprecation too since i have updated Atom and i don't really know how to fix it.
If anybody got an idea to solve it, we'll be very happy!

**Comment by rkeppner** [comment] 2017-04-03 17:25
Same issue.

**Comment by Rayree** [comment] 2017-05-08 01:33
Same issue.

**Comment by nirix** [comment] 2017-05-09 05:49
Sorry for taking so long to get to this, I don't use Atom as often as I used to. I will get this fixed within the next day.

**Comment by nirix** [comment] 2017-05-26 01:33
I have not yet been able to reproduce this issue.

**Closed** 2017-07-17 01:48 UTC
Labels: bug
